### PR TITLE
Log actions taken by users

### PR DESCRIPTION
**Pull request by jonavellecuerdo**
### Purpose and background context
Log messages indicating important actions taken by the `current_user` (i.e., the logged in user). The application will log:
* When the user **executes a `<run_type>` run and the corresponding task ID** 
* When the user **checks the status of a task and the corresponding task ID**
* When the user **logs out**
   * As noted in https://github.com/MITLibraries/alma-sapinvoices-ui/pull/60, we are not adding a `logout` button at this time since the ALB is handling all authentication and authorization for us.

It is also worth noting that these logs are sent to the CloudWatch log group for the **Flask UI**; the log streams named with the task ID are part of the **CLI** log group, which is why the task ID is included in the logged messages introduced in these updates.

### How can a reviewer manually see the effects of these changes?
1. Visit https://sapinvoices.stage.mitlibrary.net/! 🤓 The home page should welcome _you_! 
   **Note:** Requires connection to GlobalProtect VPN.
3. Review screenshot of CloudWatch log stream message example.
Screenshot 2024-08-22 at 1 56 39 PM
   **Note:** Hoping to speak with Infra to figure out the best way to organize these logged messages (e.g., the Sentry configure message gets logged for every visited page 🤔 -- but out of scope for this PR!)

### Includes new or updated dependencies?
NO

### Changes expectations for external applications?
NO

### What are the relevant tickets?
- https://mitlibraries.atlassian.net/browse/IN-1034

### Developer
- [x] All new ENV is documented in README
- [ ] All new ENV has been added to staging and production environments
- [x] All related Jira tickets are linked in commit message(s)
- [x] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer(s)
- [ ] The commit message is clear and follows our guidelines (not just this PR message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The provided documentation is sufficient for understanding any new functionality introduced
- [ ] Any manual tests have been performed and verified
- [ ] New dependencies are appropriate or there were no changes

### CODE REVIEW

**Review by ghukill — APPROVED** [review]
Looks good to me.  Nice work on the logging function, the check for authenticated user, etc.

I sat for awhile with the idea of asking your thoughts @jonavellecuerdo about more structured logging, something like:

```json
{
  "user":"<email or name>",
  "action":"<email or name> executed run type 'review'"
}
```

With the thinking that it could be easier to parse at scale.  You could parse lots of cloudwatch logs, perhaps filter to the user, etc.  But... I think it's unlikely we'll be doing that often.  I imagine the auditing / logging is most helpful to look into an "incident" perhaps.

While I think structured logging is something to consider as a _general practice_, across all our apps, we don't do it often as-is.  Therefore, I'm good with continuing sort of ad-hoc logging in this way.

Semi-related: if we were _really_ concerned about auditing, we might even consider a storage mechanism for this data outside of Cloudwatch logs that is more structured.  

It may be worth a question to stakeholders when ya'll meet about auditing; how frequent they think it would happen, what we need to note and record, etc.  Perhaps that might lead to revisiting auditing for this app at a later date.  But taken altogether, I think these log statements perform the thing we need at the moment: who did what, and when.

Approved!

**Review by ehanson8 — APPROVED** [review]
Looks great and very clear tests!

**Comment by ehanson8** [comment]
> With the thinking that it could be easier to parse at scale. You could parse lots of cloudwatch logs, perhaps filter to the user, etc. But... I think it's unlikely we'll be doing that often. I imagine the auditing / logging is most helpful to look into an "incident" perhaps.

We did play around with the `structlog` library in some apps a few years ago but it didn't really catch on precisely because we didn't really ever need to analyze the logs at scale

**Comment by jonavellecuerdo** [comment]
@ghukill Thank you for bringing this up! I'll make sure to ask stakeholders how / if they find these logs helpful for their own use cases (e.g., auditing). 🤔 As expressed above, I do think the changes here are what just what we need _for now_.

**Comment by ghukill** [comment]
> > With the thinking that it could be easier to parse at scale. You could parse lots of cloudwatch logs, perhaps filter to the user, etc. But... I think it's unlikely we'll be doing that often. I imagine the auditing / logging is most helpful to look into an "incident" perhaps.
> 
> We did play around with the `structlog` library in some apps a few years ago but it didn't really catch on precisely because we didn't really ever need to analyze the logs at scale

Never heard of `structlog`!  Looks pretty neat. Agree it doesn't feel like we need it now, but could be interesting to revisit sometime.

**Pull request merged**
